name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run amp.sh
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Run amp.sh
      run: |
        ./amp.sh
