name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run amp.sh
    runs-on: ubuntu-20.04

    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Checkout Code
      uses: actions/checkout@v2

    #php_modules_moodle_required="php-{curl,ctype,dom,iconv,json,mbstring,pcre,simplexml,spl,xml,zip}"
    #php_modules_moodle_recommended="php-{intl,gd,openssl,soap,tokenizer,xmlrpc}"
    #php_modules_moodle_conditional="php-mysql php-odbc php-pgsql php-ldap php-ntlm"
    #php_modules_moodle_conditional="php-mysql"
    #php_modules_memcached="php-memcached"
    #php_modules_opensharing="php-{apcu,bz2,geoip,gmp,msgpack,pear,xml}"
    # https://github.com/shivammathur/setup-php/wiki/Php-extensions-loaded-on-ubuntu-20.04#php-74
    # List of default PHP Modules
    #php_modules_moodle_required="php-{,}"
    #php_modules_moodle_recommended="php-{,,,,,}"
    #php_modules_moodle_conditional="php- php- php- php- php-ntlm"
    #php_modules_moodle_conditional="php-mysql"
    #php_modules_memcached="php-"
    #php_modules_opensharing="php-{,geoip,,,pear,"

    - name: Setup PHP
      uses: shivammathur/setup-php@verbose
      with:
        php-version: '7.4'
        extensions: php-fpm

    - name: Run amp.sh
      run: |
        [[ -f ./amp.sh ]] && ./amp.sh || echo "./amp.sh file not present"
