name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run amp.sh
    runs-on: ubuntu-20.04

    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Checkout Code
      uses: actions/checkout@v2

    # https://github.com/shivammathur/setup-php/wiki/Php-extensions-loaded-on-ubuntu-20.04#php-74
    # List of default PHP Modules
    # Has mysqli not mysql
    # May need geoip, ntlm, pear
    # GH Actions image already has php7.4-fpm
    # php7.4-fpm is already the newest version (7.4.13-1+ubuntu20.04.1+deb.sury.org+1).

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run amp.sh
      run: |
        [[ -f ./amp.sh ]] && sudo ./amp.sh || echo "./amp.sh file not present"

    - name: Set test site
      run: |
        [[ -f ./virtualhost.sh ]] && sudo ./virtualhost.sh create myblog.dev wordpress || echo "./virtualhost.sh file not present"
