name: Lint

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
